apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-name
spec:
  storageClass: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resource:
    requests:
      storage: 10Gi